# Generated by Django 3.2.11 on 2022-04-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_delete_employee'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
